name: Update hosts.txt

on:
  schedule:
    - cron: "0 15 * * *"

  push:
    branches: ["main"]
    paths:
      - .github/workflows/update.yml
      - update.sh

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission for update.sh
        run: chmod +x update.sh

      - name: Update hosts
        run: ./update.sh

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add hosts.json
          git add hosts.csv
          git commit -am "Update hosts"
          git push
